name: Release .zip file
on:
  push:
    branches: [main]
jobs:
  release_zip:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Copy .package files from src into build folder
      - name: Copy files from src/ into temporary build/ folder
        run: |
          mkdir build
          find src/ -name '*.package' -exec cp -prv '{}' 'build/' ';'

      # Grab files from build/ folder and release in a ZIP folder
      - name: Zip and Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'release.zip'
          path: 'build'

      # Remove the build folder
      - name: Tidy up
        run: rm -rf build/
